name: Publish Python package

on:
  push:
    branches:
      - main  # Yalnız main branch-ə push ediləndə işləyəcək

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Python versiyasını uyğun olaraq seçin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        run: |
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
